import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const enc=new TextEncoder(), dec=new TextDecoder();
const b64=(u:Uint8Array)=>btoa(String.fromCharCode(...u)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const unb64=(s:string)=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')+'==='.slice((s.length+3)%4)),c=>c.charCodeAt(0));
async function key(){const secret=Deno.env.get('SSO_SECRET'); if(!secret||secret.length<32) throw new Error('SSO_SECRET must be at least 32 characters.'); const h=await crypto.subtle.digest('SHA-256',enc.encode(secret)); return crypto.subtle.importKey('raw',h,{name:'AES-GCM'},false,['encrypt','decrypt']);}
async function seal(obj:any){const iv=crypto.getRandomValues(new Uint8Array(12)); const ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(),enc.encode(JSON.stringify(obj)))); return b64(iv)+'.'+b64(ct);}
async function openTicket(t:string){const [a,b]=t.split('.'); if(!a||!b) throw new Error('Invalid ticket.'); const pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(a)},await key(),unb64(b)); return JSON.parse(dec.decode(pt));}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors}); try{const body=await req.json(); if(body.action==='create'){const auth=req.headers.get('Authorization')||''; const access=body.access_token; if(!auth.startsWith('Bearer ')||!access) throw new Error('Authentication required.'); const supabase=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')!); const {data,error}=await supabase.auth.getUser(access); if(error||!data.user) throw new Error('Invalid Ethan ID session.'); const ticket=await seal({sub:data.user.id,access_token:access,refresh_token:body.refresh_token,target:body.target||'erp',exp:Date.now()+60000,nonce:crypto.randomUUID()}); return Response.json({ticket,expires_in:60},{headers:cors});}
 if(body.action==='exchange'){const p=await openTicket(body.ticket||''); if(Date.now()>p.exp) throw new Error('Ethan ID handoff expired.'); if((body.target||'erp')!==p.target) throw new Error('Invalid handoff target.'); return Response.json({access_token:p.access_token,refresh_token:p.refresh_token},{headers:cors});} throw new Error('Unsupported action.');}catch(e){return Response.json({error:e.message||'SSO error'},{status:400,headers:cors});}});
